# Generated by Django 4.2.6 on 2023-11-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('summonerLevel', models.IntegerField(default=0)),
                ('profileIconId', models.IntegerField(default=0)),
                ('times_searched', models.IntegerField(default=0)),
            ],
        ),
    ]
